### ISSUE TITLE
ksync keeps losing connection

### ISSUE THREAD

**Issue by scones** [vapor-ware/ksync#247] opened 2018-11-22 14:53 UTC
log entry from syncthing:
```
[PETWT] 12:29:12 INFO: Connection to SW2ODE5-ZSCWQH4-NQWRLHS-4465ZAM-N6FCE55-JU2QTUL-QPG6VL4-A6QZRQ5 at 127.0.0.1:22000-127.0.0.1:49714/tcp-server closed: reading length: EOF
[PETWT] 12:29:12 VERBOSE: Disconnected from device SW2ODE5-ZSCWQH4-NQWRLHS-4465ZAM-N6FCE55-JU2QTUL-QPG6VL4-A6QZRQ5
```

log entry from watch command:
```
ERRO[3458] lost connection to cluster                    ContainerName= LocalPath=/home/scones/vm/pontos LocalReadOnly=true Name=just-oryx Namespace=application-development Pod= Reload=true RemotePath=/var/www/html RemoteReadOnly=false Selector="[application_name=pontos-app]"
INFO[3458] signal loss dectected. shutting down
```

relevant stuff:
```
ksync:
        Version:    Release
        Go Version: go1.11
        Git Commit: c6d2e34
        Git Tag:    0.3.2-hotfix
        Built:      Mon Oct  1 19:19:36 +0000 2018
        OS/Arch:    linux/amd64
service:
        Version:    Release
        Go Version: go1.11
        Git Commit: c6d2e34
        Git Tag:    0.3.2-hotfix
        Built:      Mon Oct  1 19:15:00 +0000 2018
```

additional relevant stuff:
kubernetes: 1.12.2
minikube: minikube version: v0.30.0 (with driver `none`)
just 1 pod

**Comment by scones** [comment] 2018-11-22 14:54
retry on the syncthing log:

```
[PETWT] 12:29:12 INFO: Connection to SW2ODE5-ZSCWQH4-NQWRLHS-4465ZAM-N6FCE55-JU2QTUL-QPG6VL4-A6QZRQ5 at 127.0.0.1:22000-127.0.0.1:49714/tcp-server closed: reading length: EOF
[PETWT] 12:29:12 VERBOSE: Disconnected from device SW2ODE5-ZSCWQH4-NQWRLHS-4465ZAM-N6FCE55-JU2QTUL-QPG6VL4-A6QZRQ5                    
```

**Comment by timfallmk** [comment] 2018-12-11 18:43
Is this still an issue? If not I'll close it and you can reopen when it happens again.

**Comment by timfallmk** [comment] 2018-12-17 20:16
Feel free to reopen if needed.

**Comment by kbernst30** [comment] 2018-12-22 21:31
I just encountered this again. The exact same error above. Happened 3 times today. There is definitely something amiss.

**Comment by kbernst30** [comment] 2019-01-07 02:45
There is zero condition that I can tell. It happens constantly. I have to restart several times a day. I am using Docker for Mac Kubernetes integration if it helps at all

**Comment by timfallmk** [comment] 2019-01-09 19:51
Interesting. I can't replicate it.

Oh, if you're using a laptop and it goes to sleep, that could cause issues with the cluster. That's a known problem with how Docker Kubernetes works. Similar symptoms here: https://github.com/vapor-ware/ksync/issues/143#issuecomment-373132906

**Comment by scones** [comment] 2019-01-09 22:21
it happens without a sleep as well.

The counter in the logs (whatever it counts) goes up to 1000 to 3000 and ksync stops working in that range at a random count.

As one has to restart it several times a day during a usual workday, its obvious the system sleep is not the cause.

**Comment by timfallmk** [comment] 2019-01-10 00:54
What counter are you referring to? Maybe a log dump (with some sort of timeline for actions) would be helpful here.

**Comment by kbernst30** [comment] 2019-01-10 17:30
Perhaps he means the number in the INFO log brackets? I see something like this:

```
INFO[2856] updating                                      pod=test-pod-7db9485d8c-2cn68 spec=test
INFO[2856] update complete                               pod=test-pod-7db9485d8c-2cn68 spec=test
ERRO[2932] lost connection to cluster                    ContainerName= LocalPath={...} LocalReadOnly=false Name=test Namespace=default Pod= Reload=false RemotePath=/home/web/src RemoteReadOnly=false Selector="[app.kubernetes.io/name=test]"
INFO[2932] signal loss dectected. shutting down
```

**Comment by timfallmk** [comment] 2019-01-10 21:43
@kbernst30 Ah, good point. Those are actually timestamps coming from the log formatter. We use github.com/sirupsen/logrus to do logging, and this is an default option.

**Comment by scones** [comment] 2019-01-13 11:17
Yes, the number in the square brackets. i assumed those are counters.

**Comment by kbernst30** [comment] 2019-01-14 21:51
Not sure what other info you need but perhaps this will be helpful:

Docker for Mac v2.0.0.0-mac81 
Docker Engine v18.09.0
Kubernetes v1.10.3
Ksync Release 0.3.2-hotfix

```
ksync:
	Version:    Release
	Go Version: go1.11
	Git Commit: c6d2e34
	Git Tag:    0.3.2-hotfix
	Built:      Mon Oct  1 19:19:36 +0000 2018
	OS/Arch:    darwin/amd64
service:
	Version:    Release
	Go Version: go1.11.2
	Git Commit: c6d2e34
	Git Tag:    0.3.2-hotfix
	Built:      Tue Nov 27 22:02:35 +0000 2018
```

**Comment by timfallmk** [comment] 2019-01-14 21:55
@kbernst30 Thanks. Mostly what I'm looking for is under what operating conditions this happens. Does it happen when you leave the cluster for a while, when you're changing a lot of files, when you're quickly rebooting containers, etc.

As I said before, I think we should concentrate on the cluster itself to start, as it seems to be a problem with pod restarts not `ksync`.

**Comment by kbernst30** [comment] 2019-01-14 22:00
Well in my case I'm actually using an interpreted code base so i've disabled reloading of the containers. I also have set the remote folder to read only I believe (forgive me I have to find the settings i used to create the initial spec). 

It seems to happen after a while of idle time. It does happen more often if the folder syncs occur more frequently.

**Comment by timfallmk** [comment] 2019-01-14 22:05
The idle time thing makes more sense to me. It's likely that docker for mac (which I believe just changed to "Docker for Desktop") does some resource management during downtime to enable running a cluster locally. Kubernetes is not designed to handle interruptions or restarts of the entire cluster well, so I suspect they may be trying to smooth the experience out.

Two thing I would try:
1. Deliberately idle or heavily use your sync to see if you can trigger the condition
2. Get the logs from k8s services (and maybe docker) from around that time if you trigger the problem

Also, it might not be relevant, but I'm running the "edge" distribution of "Docker for Desktop" and it seems to have just undergone a major update (to `Version 2.0.1.0 (30090)`) which included a full wipe and recreation of the cluster. This could indicate some API changes happening, so perhaps trying this new version after the wipe would help.

**Comment by kbernst30** [comment] 2019-01-15 14:09
I will see what I can find today from k8s logs if/when a connection loss occurs. There is also a new Docker for Desktop update so I will install that as well to see if it helps at all

**Comment by kbernst30** [comment] 2019-01-15 15:40
Starting the watcher this morning at 10:04am. DId nothing else except keeping it idle. The watcher then lost connection at 10:35am.

There was nothing specific in any log that i can see unfortunately. The following appears constantly:

```
default	10:31:04.898691 -0500	com.docker.driver.amd64-linux	Cannot identify volume corresponding to path /etc/kubernetes/scheduler.conf: lstat /private/etc/kubernetes: no such file or directory
default	10:31:04.913581 -0500	com.docker.driver.amd64-linux	Cannot identify volume corresponding to path /etc/kubernetes/controller-manager.conf: lstat /private/etc/kubernetes: no such file or directory
default	10:31:04.913642 -0500	com.docker.driver.amd64-linux	Cannot identify volume corresponding to path /usr/libexec/kubernetes/kubelet-plugins/volume/exec: lstat /usr/libexec/kubernetes: no such file or directory
default	10:31:35.062963 -0500	com.docker.driver.amd64-linux	Cannot identify volume corresponding to path /etc/kubernetes/controller-manager.conf: lstat /private/etc/kubernetes: no such file or directory
default	10:31:35.063032 -0500	com.docker.driver.amd64-linux	Cannot identify volume corresponding to path /usr/libexec/kubernetes/kubelet-plugins/volume/exec: lstat /usr/libexec/kubernetes: no such file or directory
default	10:31:35.082040 -0500	com.docker.driver.amd64-linux	Cannot identify volume corresponding to path /etc/kubernetes/scheduler.conf: lstat /private/etc/kubernetes: no such file or directory
```

But not just when the connection to the cluster is lost. I will continue to dig into other logs for something strange

**Comment by scones** [comment] 2019-01-15 16:13
as described:

I am running minikube with local read only.
I did not shutdown/idle out/suspend/hibernate the computer while this happened. in fact i was writing code and verify the changes.

**Comment by timfallmk** [comment] 2019-01-15 21:17
@kbernst30 That's very strange. Nothing there is something `ksync` uses. Are you using a CNI or network plugin on top of Docker k8s or just a plain setup from scratch?

@scones Same question to you.

My suspicion is that _something_ else is going wrong with the cluster, eventually causing a shutdown (or restart) of the `daemonSet` that contains the `ksync` cluster-side pods. That's the only thing I can think of.

**Comment by grampelberg** [comment] 2019-01-15 22:02
Sounds like the reconnect code needs a little bit of love. Is there anything happening on the network stack? Like, wifi blipping, plugging/unplugging wires?

When this happens, what is the state of the DaemonSet? Anything in the logs there?

**Comment by scones** [comment] 2019-01-16 11:32
plain setup with helm and some services (ES and MySQL) in addition to the core application `pontos`

as it just works again when i just re-do the watch:
can you just build a loop with exponential backoff into the watch command? that would mitigate the problem somewhat.

**Comment by kbernst30** [comment] 2019-01-16 15:02
i also work with helm. Just in case that information is relevant.

**Comment by timfallmk** [comment] 2019-01-16 18:14
There is reconnection code already in `ksync`, but that only works if the network is stable. As @grampelberg said, this is probably due to a network status change.

It should be easy to test, once you have everything work, change wifi networks (or cables) and see if it happens.

**Comment by scones** [comment] 2019-01-17 11:35
- there was no log entry about reconnect trials
- i am speaking of a reconnect attempt on a higher scope (ie. around the watch command, not around the connection layer, i am again assuming about the structure here)
- also i suggested and incremental backoff to avoid spamming the server

these things could be optional with command line flags..

**Comment by timfallmk** [comment] 2019-01-18 20:11
I should probably clarify, as it's not quite as simple as a reconnection.

There are a few connection pieces here. Broadly they fall into three parts:
1. Local client (probably the CLI, but can be anything consuming the API). Communicates locally with the `watch` process (see next) via a local (gRPC) port. Usually ephemeral.
2. `watch` process. This listens on a local gRPC port for commands from a client (see above) as well as spawns a child process running syncthing. Also establishes tunnels for:
 - gRPC connection to remote (`radar`) container
 - Connection to Syncthing API
 - Connection to Syncthing transfer port
3. `radar` remote process. Other end of the connection for the `watch` process.

Since there are several moving parts, "reconnection" is not as simple as it sounds. For 1, the client connection only happens when running a command, so reconnection isn't needed. For 2, the process is connecting in two different "directions", "in" (the local connection), and "out" (the remote connections). This means that disconnections can happen in several different ways. I won't go into all the possibilities, but suffice it to say the matrix is large enough.

The way we handle most of these is to drop connection error messages, with the assumption that they are transient. Since the tunnel to the cluster remains (and are built on demand), there's no need to do any fancy reconnection here. You can see this [here](https://github.com/vapor-ware/ksync/blob/2a25714d1d2f69054c3f32ea74b162b0d4290913/pkg/ksync/folder.go#L85).

What is likely happening in this case is that the change in _local_ network status causes the network adapter to reset all currently established tunnels. Since the _local_ tunnel is built when starting `watch`, restarting the process solves the issue. If the problem were with the cluster connection, you wouldn't see the error and it would just continue trying to connect.

Further evidence of this is that the above logs show your network overlay freaking out, likely for the same reason. As I said before, should be easy to test. I'll give it a shot if you haven't already.

**Comment by timfallmk** [comment] 2019-01-19 00:08
A quick bench test shows this is indeed the cause of the problem. I'm going to close out this issue.

**Closed by timfallmk** 2019-01-19 00:08 UTC
